### ISSUE TITLE
ERROR - Property 'find' does not exist on type 'MongooseModel<Calendar>'.

### ISSUE THREAD

**Issue by Vetnametz** [TypedProject/tsed-example-mongoose#1]
I have cloned project to try it

`yarn run start:dev`

[2019-09-16T10:13:46.642] [ERROR] [TSED] - src/services/calendars/CalendarsService.ts(17,43): error TS2339: Property 'find' does not exist on type 'MongooseModel<Calendar>'.
src/services/calendars/CalendarsService.ts(32,42): error TS2339: Property 'findById' does not exist on type 'MongooseModel<Calendar>'.
src/services/calendars/CalendarsService.ts(50,23): error TS2351: This expression is not constructable.
  Type 'MongooseModel<Calendar>' has no construct signatures.
src/services/calendars/CalendarsService.ts(64,26): error TS2339: Property 'find' does not exist on type 'MongooseModel<Calendar>'.
src/services/calendars/CalendarsService.ts(73,32): error TS2339: Property 'findById' does not exist on type 'MongooseModel<Calendar>'.

**Comment by Romakita** [comment]
Hello @Vetnametz 
Thanks for your issue. I forgot to add `@types/mongoose`devDependencies in package.json.
Just install @types/mongoose and it'll solve the problem :)

See you

**Comment by Vetnametz** [comment]
Thx, for your nice project!

`yarn add -D @types/mongoose`

fix this issue
